spring:
  application:
    name: ticketing-app

  mongodb:
    uri: mongodb://localhost:27017/ticketing_db

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    url: /api-docs

security:
  jwt:
    secret: change-me-please-change-me-please-32-characters-minimum
    issuer: ticketing-app
    access-token-minutes: 60
    refresh-token-days: 7

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
